name: Backend CI

on:
  pull_request:
    branches:
      - Tracksify-Dev
    paths:
      - 'backend/**'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for merge conflicts
      run: git diff --quiet || (echo "Merge conflicts found. Please resolve them before merging."; exit 1)

    - name: Check for .gitignore
      run: |
        if [ -e "backend/.gitignore" ]; then
          echo "Error: .gitignore file detected in backend. Remove it before merging.";
          exit 1;
        fi

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release